### ISSUE TITLE
Sending commands from Console Sender

### ISSUE THREAD

**Issue by coleedwards** [bizarre/honcho1#13]
When you dispatch a command with the sender as Bukkit.getServer().getConsoleSender(), the command doesn't work.

This is from plugins like anticheats + buycraft.

No errors just doesn't work, but works when you do it yourself from console.

**Comment by bizarre** [comment]
It should work, what’s your command look like? It’s worked for me in the past (specifically in the case of Buycraft), so I’m guessing there’s something off with how you’ve written the command.

**Comment by bizarre** [comment]
You could also be invoking the execute command function incorrectly (in Bukkit API).

**Comment by coleedwards** [comment]
> You could also be invoking the execute command function incorrectly (in Bukkit API).

For example, when a player purchases an unban (command is /unban <player> <reason> [-s]) the plugin attempts to do the command but it only returns Unknown command. 

Another thing I've noticed when I do a bukkit default command, both the minecraft AND the honcho usage comes up: 
![image](https://user-images.githubusercontent.com/24519375/67563732-511d4480-f6ef-11e9-845a-6232961cb6c3.png)

If it's any use, I'm using pterodactyl panel. Let me know if you need code snippets (I'm using Zoot).

**Comment by bizarre** [comment]
Yeah, are you sure you’re calling Bukkit#dispatchCommand properly? It should contain the command without the slashed prefixed. The same goes for Buycraft, if you’ve setup your packages incorrectly with the prepended slash then it’ll get passed to Bukkit as “//command” instead of “/command”, that’s why you don’t prefix commands you execute from console with a slash.

**Comment by bizarre** [comment]
Also, I’m not familiar with “Zoot”, is it a plugin that uses honcho? If so, is it using the latest version or an older one? It’s possible the version of honcho that’s compiled isn’t up-to-date, but I think the real problem is as I mentioned previously.

**Comment by coleedwards** [comment]
Realised I was using an older version, thank you for your help! :)
