### ISSUE TITLE
How do we use subcommands?

### ISSUE THREAD

**Issue by jucay** [bizarre/honcho1#6]
Can't find any example either figure out myself.

**Comment by ghost** [comment]
Example:

```JAVA
@CommandMeta(label = { "no u", "no you" }, permission = "nou.use", async = true)
```

That should work ^^

**Comment by bizarre** [comment]
See 
https://github.com/bizarre/honcho/blob/dfac2eb720d02df3ad01464203972416d6df582b/src/main/kotlin/com/qrakn/honcho/command/example/ExampleCommand.kt#L2.5
